ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'APPROVAL_REQUESTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'APPROVAL_APPROVED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'APPROVAL_REJECTED';
