ALTER TABLE "AssessmentType"
ADD COLUMN IF NOT EXISTS "includeInTotal" BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE "ClassAssessmentType"
ADD COLUMN IF NOT EXISTS "includeInTotal" BOOLEAN NOT NULL DEFAULT TRUE;
